Fix Post_Process to work with Movies
Fixed "AttributeError: PostProcessor instance has no attribute 'post_process_directory'" caused by calling self.post_process_directory instead of self.post_process_environment